### ISSUE TITLE
Have a per-forum mailing list

### ISSUE THREAD

**Issue by DavidIQ** [DavidIQ/MailingList#3]
Provide the ability to set a per-forum mailing list address instead of just a general mailing list setting.

**Comment by lazyrabbitt** [comment]
Any status on this enhancement. It is something that would be very useful.

**Comment by DavidIQ** [comment]
Will get done eventually. Does the bumping of this have anything to do with https://github.com/DavidIQ/MailingList/issues/4?  🤔

**Comment by olli395** [comment]
Thanks for this great extension.
I am yearningly waiting for the per forum ability :-)

**Comment by olli395** [comment]
Hello David,
any news about this?
I would even be ready to pay something for this (not the big budget for it, but I am sure I am not the onlyone...)
regards, Olli

**Comment by DavidIQ** [comment]
Hello,

Any monetary incentives can be done through [my thank you page](https://www.davidiq.com/support/thank-you). Otherwise this will be getting looked at soon-ish.

**Comment by olli395** [comment]
Just see your post, wanted to donate, but as I am in Romania, Paypal rejects me :-(
...Need to wait, till I am back in Germany...

**Comment by olli395** [comment]
Hello David, 
finally was able to send you a payment...
Best regards, Olli

**Comment by DavidIQ** [comment]
Ah that explains it. Thanks. Will be working on this along with ensuring 3.3 support.

**Comment by olli395** [comment]
thank you for this :-)
Best regards and a nice weekend, Olli

Am Fr., 21. Feb. 2020 um 15:17 Uhr schrieb David Colón <
notifications@github.com>:

**Comment by DavidIQ** [comment]
https://github.com/DavidIQ/MailingList/releases/tag/2.0.0

**Comment by olli395** [comment]
Hello David,
Thank you for this. How can I make this running under 3.2.9?
It seems not to work, as I haven´t updated to 3.3.0...
Best regards, and thank you again, Olli

Am Sa., 29. Feb. 2020 um 19:45 Uhr schrieb David Colón <
notifications@github.com>:

**Comment by DavidIQ** [comment]
This was updated and tested in 3.2.9 first. What isn't working?

**Comment by olli395** [comment]
no, but I´ll try again... Maybe I made a mistake...


Am Mo., 2. März 2020 um 15:29 Uhr schrieb David Colón <
notifications@github.com>:

**Comment by olli395** [comment]
just tried again... And it works now...Magic :-)
Thank you soo much for this!
(I don´t know what I did wrong yesterday...)

Am Mo., 2. März 2020 um 15:32 Uhr schrieb Ol Li <
olivier.liede@googlemail.com>:

**Comment by olli395** [comment]
Hi David, I just translated into german :-)
Best regards, Olli

Am Mo., 2. März 2020 um 15:38 Uhr schrieb Ol Li <
olivier.liede@googlemail.com>:

**Comment by DavidIQ** [comment]
Great, feel free to post it here: https://www.phpbb.com/customise/db/extension/mailinglist/support/topic/160806

**Comment by olli395** [comment]
ok, will do :-)

Am Di., 3. März 2020 um 15:17 Uhr schrieb David Colón <
notifications@github.com>:
